# Generated by Django 5.2.4 on 2025-08-01 07:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('chatbot', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='user',
            old_name='email',
            new_name='content',
        ),
        migrations.RenameField(
            model_name='user',
            old_name='name',
            new_name='role',
        ),
    ]
