# Generated by Django 5.2.4 on 2025-08-01 07:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chatbot', '0002_rename_email_user_content_rename_name_user_role'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='content',
            field=models.CharField(unique=True),
        ),
    ]
